# Nouvelles caractéristiques
new_features = ['Barbe de 3 jours', 'Sourcils Arqués', None, 'Cernes', 'Chauve', 'Frange', 'Grosses Levres', 'Gros Nez', 'Cheveux noirs', 'Cheveux blonds', None, 
                'Cheveux Bruns', 'Sourcils Broussailleux', None, 'Double Menton', 'Lunettes', 'Bouc', 'Cheveux Gris', 'Maquillage', 'Pommettes Hautes', 'Homme', 
                'Bouche Entrouverte', 'Moustache', 'Yeux Etroits', 'Pas de barbe', 'Visage Oval', None, 'Nez Pointu', 'Calvitie', None, 
                None, 'Sourire', 'Cheveux Lisses', 'Cheveux Ondules', 'Boucles d oreilles', 'Chapeau', 'Rouge A Levres', 'Collier', 'Cravate', 
                'Jeune']

features = ['Barbe de 3 jours', 'Sourcils Arqués', 'Attirant', 'Cernes', 'Chauve', 'Frange', 'Grosses Levres', 'Gros Nez', 'Cheveux noirs', 'Cheveux blonds', 'Flou', 
                'Cheveux Bruns', 'Sourcils Broussailleux', 'Dodu', 'Double Menton', 'Lunettes', 'Bouc', 'Cheveux Gris', 'Maquillage', 'Pommettes Hautes', 'Homme', 
                'Bouche Entrouverte', 'Moustache', 'Yeux Etroits', 'Pas de barbe', 'Visage Oval', 'Peau Pale', 'Nez Pointu', 'Calvitie', 'Joues Roses', 
                'Rouflaquettes', 'Sourire', 'Cheveux Lisses', 'Cheveux Ondules', 'Boucles d oreilles', 'Chapeau', 'Rouge A Levres', 'Collier', 'Cravate', 
                'Jeune']

# Nouvelles questions pour les caractéristiques
new_questions = {
    'Barbe de 3 jours': 'Le personnage a-t-il une barbe de trois jours?',
    'Sourcils Arqués': 'Le personnage a-t-il des sourcils arqués?',
    'Attirant': 'Le personnage est-il considéré comme attirant?',
    'Cernes': 'Le personnage a-t-il des cernes sous les yeux?',
    'Chauve': 'Le personnage est-il chauve?',
    'Frange': 'Le personnage a-t-il une frange?',
    'Grosses Levres': 'Le personnage a-t-il de grosses lèvres?',
    'Gros Nez': 'Le personnage a-t-il un gros nez?',
    'Cheveux noirs': 'Le personnage a-t-il des cheveux noirs?',
    'Cheveux blonds': 'Le personnage a-t-il des cheveux blonds?',
    'Flou': "L'image est-elle floue?",
    'Cheveux Bruns': 'Le personnage a-t-il des cheveux bruns?',
    'Sourcils Broussailleux': 'Le personnage a-t-il des sourcils broussailleux?',
    'Dodu': 'Le personnage est-il dodu?',
    'Double Menton': 'Le personnage a-t-il un double menton?',
    'Lunettes': 'Le personnage porte-t-il des lunettes?',
    'Bouc': 'Le personnage a-t-il un bouc?',
    'Cheveux Gris': 'Le personnage a-t-il des cheveux gris?',
    'Maquillage': 'Le personnage porte-t-il du maquillage?',
    'Pommettes Hautes': 'Le personnage a-t-il des pommettes hautes?',
    'Homme': 'Le personnage est-il un homme?',
    'Bouche Entrouverte': 'La bouche du personnage est-elle légèrement ouverte?',
    'Moustache': 'Le personnage a-t-il une moustache?',
    'Yeux Etroits': 'Le personnage a-t-il des yeux étroitements fermés?',
    'Pas de barbe': 'Le personnage est-il rasé de près (ou n\'a pas de barbe)?',
    'Visage Oval': 'Le personnage a-t-il un visage ovale?',
    'Peau Pale': 'Le personnage a-t-il la peau pâle?',
    'Nez Pointu': 'Le personnage a-t-il un nez pointu?',
    'Calvitie': 'Le personnage a-t-il un début de calvitie?',
    'Joues Roses': 'Le personnage a-t-il des joues roses?',
    'Rouflaquettes': 'Le personnage a-t-il des rouflaquettes?',
    'Sourire': 'Le personnage sourit-il?',
    'Cheveux Lisses': 'Le personnage a-t-il des cheveux raides?',
    'Cheveux Ondules': 'Le personnage a-t-il des cheveux ondulés?',
    'Boucles d oreilles': "Le personnage porte-t-il des boucles d'oreilles?",
    'Chapeau': 'Le personnage porte-t-il un chapeau?',
    'Rouge A Levres': 'Le personnage porte-t-il du rouge à lèvres?',
    'Collier': 'Le personnage porte-t-il un collier?',
    'Cravate': 'Le personnage porte-t-il une cravate?',
    'Jeune': 'Le personnage est-il jeune?'
}

answers = {
    'Barbe de 3 jours': ['Non, le personnage n\'a pas de barbe de trois jours.', 'Oui, le personnage a une barbe de trois jours.'],
    'Sourcils Arqués': ['Non, le personnage n\'a pas des sourcils arqués.', 'Oui, le personnage a des sourcils arqués.'],
    'Attirant': ['Non, le personnage n\'est pas considéré comme attirant.', 'Oui, le personnage est considéré comme attirant.'],
    'Cernes': ['Non, le personnage n\'a pas de cernes sous les yeux.', 'Oui, le personnage a des cernes sous les yeux.'],
    'Chauve': ['Non, le personnage n\'est pas chauve.', 'Oui, le personnage est chauve.'],
    'Frange': ['Non, le personnage n\'a pas de frange.', 'Oui, le personnage a une frange.'],
    'Grosses Levres': ['Non, le personnage n\'a pas de grosses lèvres.', 'Oui, le personnage a de grosses lèvres.'],
    'Gros Nez': ['Non, le personnage n\'a pas un gros nez.', 'Oui, le personnage a un gros nez.'],
    'Cheveux noirs': ['Non, le personnage n\'a pas des cheveux noirs.', 'Oui, le personnage a des cheveux noirs.'],
    'Cheveux blonds': ['Non, le personnage n\'a pas des cheveux blonds.', 'Oui, le personnage a des cheveux blonds.'],
    'Flou': ['Non, l\'image n\'est pas floue.', 'Oui, l\'image est floue.'],
    'Cheveux Bruns': ['Non, le personnage n\'a pas des cheveux bruns.', 'Oui, le personnage a des cheveux bruns.'],
    'Sourcils Broussailleux': ['Non, le personnage n\'a pas des sourcils broussailleux.', 'Oui, le personnage a des sourcils broussailleux.'],
    'Dodu': ['Non, le personnage n\'est pas dodu.', 'Oui, le personnage est dodu.'],
    'Double Menton': ['Non, le personnage n\'a pas de double menton.', 'Oui, le personnage a un double menton.'],
    'Lunettes': ['Non, le personnage ne porte pas de lunettes.', 'Oui, le personnage porte des lunettes.'],
    'Bouc': ['Non, le personnage n\'a pas de bouc.', 'Oui, le personnage a un bouc.'],
    'Cheveux Gris': ['Non, le personnage n\'a pas des cheveux gris.', 'Oui, le personnage a des cheveux gris.'],
    'Maquillage': ['Non, le personnage ne porte pas de maquillage.', 'Oui, le personnage porte du maquillage.'],
    'Pommettes Hautes': ['Non, le personnage n\'a pas des pommettes hautes.', 'Oui, le personnage a des pommettes hautes.'],
    'Homme': ['Non, le personnage n\'est pas masculin.', 'Oui, le personnage est masculin.'],
    'Bouche Entrouverte': ['Non, la bouche du personnage n\'est pas légèrement ouverte.', 'Oui, la bouche du personnage est légèrement ouverte.'],
    'Moustache': ['Non, le personnage n\'a pas de moustache.', 'Oui, le personnage a une moustache.'],
    'Yeux Etroits': ['Non, le personnage n\'a pas des yeux étroitement fermés.', 'Oui, le personnage a des yeux étroitement fermés.'],
    'Pas de barbe': ['Non, le personnage n\'est pas rasé de près.', 'Oui, le personnage est rasé de près.'],
    'Visage Oval': ['Non, le personnage n\'a pas un visage ovale.', 'Oui, le personnage a un visage ovale.'],
    'Peau Pale': ['Non, le personnage n\'a pas la peau pâle.', 'Oui, le personnage a la peau pâle.'],
    'Nez Pointu': ['Non, le personnage n\'a pas un nez pointu.', 'Oui, le personnage a un nez pointu.'],
    'Calvitie': ['Non, le personnage n\'a pas un début de calvitie.', 'Oui, le personnage a un début de calvitie.'],
    'Joues Roses': ['Non, le personnage n\'a pas des joues roses.', 'Oui, le personnage a des joues roses.'],
    'Rouflaquettes': ['Non, le personnage n\'a pas des rouflaquettes.', 'Oui, le personnage a des rouflaquettes.'],
    'Sourire': ['Non, le personnage ne sourit pas.', 'Oui, le personnage sourit.'],
    'Cheveux Lisses': ['Non, le personnage n\'a pas des cheveux raides.', 'Oui, le personnage a des cheveux raides.'],
    'Cheveux Ondules': ['Non, le personnage n\'a pas des cheveux ondulés.', 'Oui, le personnage a des cheveux ondulés.'],
    'Boucles d oreilles': ['Non, le personnage ne porte pas de boucles d\'oreilles.', 'Oui, le personnage porte des boucles d\'oreilles.'],
    'Chapeau': ['Non, le personnage ne porte pas de chapeau.', 'Oui, le personnage porte un chapeau.'],
    'Rouge A Levres': ['Non, le personnage ne porte pas de rouge à lèvres', 'Oui, le personnage porte du rouge à lèvres.'],
    'Collier': ['Non, le personnage ne porte pas de collier.', 'Oui, le personnage porte un collier.'],
    'Cravate': ['Non, le personnage ne porte pas de cravate.', 'Oui, le personnage porte une cravate.'],
    'Jeune': ['Non, le personnage n\'est pas jeune.', 'Oui, le personnage est jeune.'],
    }


# Proba features
proba_features = [  0.9008, 0.7902, 0.7648, 0.805, 0.9752, 0.9252, 0.7598, 0.8002, 0.874, 
                    0.9284, 0.9532, 0.8348, 0.8916, 0.9464, 0.9542, 0.9752, 0.9508, 0.9698, 0.8886, 0.84, 
                    0.9406, 0.8578, 0.9622, 0.8882, 0.9098, 0.722, 0.9618, 0.7334, 0.9222, 0.9416, 0.9506, 
                    0.8876, 0.7758, 0.7714,0.8364, 0.975, 0.9052, 0.858, 0.946, 0.8372]

